/*
 * Coverage:
 * 1. selection-stmt
 * 2. iteration-stmt
 * 3. return-stmt
 * 4. call
 * 5. those can be generated by expression
 */

int proc3(int a, int b, int c, int d){
    return a * b + c - d;
}

int proc2(void){
    /* 
     * right interpretation is 
     * (1+2-3) >= (4*5/proc(123))
     */
    return 1+2-3 >= 4*5/proc3(1,2,3, 1+1);
}

int proc1(void)
{
    if(1 != 2){
        int ret;
        ret = proc2();
        output(ret);
        return 3;
    }
    else{
        int i;
        i = 123;
        while(i < 126){
            i = i + 1;
        }
    }
}

void main(void){
    output(proc1());
    return;
}
