/*
 * Coverage:
 * 1. selection-stmt
 * 2. iteration-stmt
 * 3. return-stmt
 * 4. call
 * 5. those can be generated by expression
 */

int proc1(int i)

int proc2(void){
    /* 
     * right interpretation is 
     * (1+2-3) >= (4*5/proc(123))
     */
    return 1+2-3 >= 4*5/proc1(123)+proc3(1,2,3, 1+1);
}

{
    if(1 != 2){
        int ret;
        ret = proc2();
    }
    else{
        while(1){
            int i;
            i = 123;
            123;
        }
    }
}